### ISSUE TITLE
Won't download Diabetes.csv in Jupiter MacOS

### ISSUE THREAD

**Issue by melanki** [alu042/DAT158ML#1]
/Part1-intro/DAT158-Part1-simple_examples.ipynb 

Won't download file "Dataset.csv" into "./Part1-intro/data/" since directory doesnt't exist.

Can be fixed by 

1. Creating data directory in repo
2. Download file into an existing directory
3. Manually create data directory locally

**Comment by alu042** [comment]
I added a cell to the notebook to create the 'data' directory. Thanks!
