### ISSUE TITLE
Update setup.md

### ISSUE THREAD

**Issue by Ichtil** [alu042/DAT158ML#2]
Setup.md says at the end to test the installation by opening notebook 0.0-test.ipynb in the notebooks folder, but notebooks folder doesn't exist and the notebook is in the root folder.

> Go through the notebook 0.0-test.ipynb in the notebooks folder:
>
>cd notebooks
>jupyter notebook
>You can alternatively use JupyterLab:
>
>cd notebooks
>jupyter lab

**Comment by alu042** [comment]
Thanks, fixed!
